# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3_primeri', '0002_auto_20170901_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
